

// Google API key for CloudVision and Knowledge Graph
export const GOOGLE_API = "AIzaSyAiezXiOJMvOtSK4eMoXKfUvX4yY4RW5SQ"

// FourSquare API key
export const FS_CLIENT_ID = 'EECH5IF2TSK01WV2DQUKIRNT5CUVRTH0AVVDFM521E32ZVPH'
export const FS_CLIENT_PW = '1LL20JSTUVM1BM4G30E0KMN1QBKU3ZDVLMO1OP5QIPWCQEOK'
